kotlin.code.style=official
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
org.jetbrains.compose.experimental.macos.enabled=true

GROUP=dev.brahmkshatriya.kmplayer
VERSION_NAME=0.1.0-SNAPSHOT

kotlinVersion=2.4.20
androidPluginVersion=9.3.3
composeUiVersion=1.13.0-alpha01
composeNativeVersion=1.13.0-alpha10
mavenPublishPluginVersion=0.37.0
coroutinesVersion=1.10.2
kotlinxBrowserVersion=0.5.0
media3Version=1.11.1
hlsJsVersion=1.7.3
androidCompileSdk=37
androidMinSdk=24
androidSdkPlatformVersion=37.0
androidBuildToolsVersion=37.0.0

POM_NAME=kmplayer
POM_DESCRIPTION=Kotlin Multiplatform audio and video playback using the native media stack on each platform, with HLS support and Compose integration.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/brahmkshatriya/kmplayer

POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo

POM_SCM_URL=https://github.com/brahmkshatriya/kmplayer
POM_SCM_CONNECTION=scm:git:https://github.com/brahmkshatriya/kmplayer.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/brahmkshatriya/kmplayer.git

POM_DEVELOPER_ID=brahmkshatriya
POM_DEVELOPER_NAME=Brahm Kshatriya
POM_DEVELOPER_URL=https://github.com/brahmkshatriya
